version: "3.9"
services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=yua
    - POSTGRES_PASSWORD=senha123
    - POSTGRES_DB=postgresdb
    volumes:
    - pgdata:/data/postgres
  app:
    build: .
    container_name: crudnodejs
    ports:
      - "3333:3333"
    volumes:
      - .:/user/app
    links:
    - database
    depends_on:
      - database


volumes:
  pgdata: